---
- name: create SSL directory
  file:
    dest: "{{ consul_tls_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- block:
  - name: copy CA certificate
    copy:
      src: "{{ consul_src_files }}/{{ consul_ca_crt }}"
      dest: "{{ consul_tls_dir }}/{{ consul_ca_crt }}"
      owner: "{{ consul_user }}"
      group: "{{ consul_group }}"
      mode: 0644

  - name: copy server certificate
    copy:
      src: "{{ consul_src_files }}/{{ consul_server_crt }}"
      dest: "{{ consul_tls_dir }}/{{ consul_server_crt }}"
      owner: "{{ consul_user }}"
      group: "{{ consul_group }}"
      mode: 0644

  - name: copy server key
    copy:
      src: "{{ consul_src_files }}/{{ consul_server_key }}"
      dest: "{{ consul_tls_dir }}/{{ consul_server_key }}"
      owner: "{{ consul_user }}"
      group: "{{ consul_group }}"
      mode: 0600

  when: consul_copy_keys == true

- name: write TLS configuration
  template:
    src: config_tls.json.j2
    dest: "{{ consul_config_path }}/{{ item }}/config_tls.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group}}"
  with_items:
    - bootstrap
    - client
    - server
